# Generated by Django 3.1.1 on 2020-09-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shthols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('also_known_as', models.CharField(max_length=50)),
                ('as_seen_in', models.CharField(max_length=200)),
                ('pestilence', models.CharField(max_length=200)),
                ('danger_level', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
