# Generated by Django 3.1.1 on 2020-09-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shthols',
            new_name='Place',
        ),
    ]
